/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as SpacesSlugRouteImport } from './routes/spaces_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSlugRoute = SpacesSlugRouteImport.update({
  id: '/spaces_/$slug',
  path: '/spaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/spaces': typeof SpacesRoute
  '/spaces/$slug': typeof SpacesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/spaces': typeof SpacesRoute
  '/spaces/$slug': typeof SpacesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/spaces': typeof SpacesRoute
  '/spaces_/$slug': typeof SpacesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/events'
    | '/login'
    | '/members'
    | '/spaces'
    | '/spaces/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/events'
    | '/login'
    | '/members'
    | '/spaces'
    | '/spaces/$slug'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/events'
    | '/login'
    | '/members'
    | '/spaces'
    | '/spaces_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  SpacesRoute: typeof SpacesRoute
  SpacesSlugRoute: typeof SpacesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces_/$slug': {
      id: '/spaces_/$slug'
      path: '/spaces/$slug'
      fullPath: '/spaces/$slug'
      preLoaderRoute: typeof SpacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  SpacesRoute: SpacesRoute,
  SpacesSlugRoute: SpacesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
